add yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,6 +6,7 @@ on:
       - develop
       - staging
       - prod
+
 jobs:
   terraform-deploy:
     name: Deploy to S3 and Invalidate CloudFront
@@ -30,17 +31,20 @@ jobs:
             echo "ENV_DIR=staging" >> $GITHUB_ENV
             echo "ENV_BUCKET=uthman-staging-2025" >> $GITHUB_ENV
             echo "DISTRIBUTION_ID=${{ secrets.STAGING_CLOUDFRONT_DISTRIBUTION_ID }}" >> $GITHUB_ENV
-          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
             echo "ENV_DIR=prod" >> $GITHUB_ENV
             echo "ENV_BUCKET=uthman-production-2025" >> $GITHUB_ENV
             echo "DISTRIBUTION_ID=${{ secrets.PROD_CLOUDFRONT_DISTRIBUTION_ID }}" >> $GITHUB_ENV
+          else
+            echo "ERROR: Branch '${{ github.ref }}' not configured for deploy. Exiting."
+            exit 1
           fi
 
       - name: Terraform Init
         run: cd $ENV_DIR && terraform init
 
       - name: Terraform Apply
-        run: cd $ENV_DIR && terraform apply -auto-approve -var="uthman-production-2025=${{ env.ENV_BUCKET }}"
+        run: cd $ENV_DIR && terraform apply -auto-approve -var="bucket_name=${{ env.ENV_BUCKET }}"
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -52,3 +56,4 @@ jobs:
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
